### ISSUE TITLE
News Updater error

### ISSUE THREAD

**Issue by Amplificator** [crazy-max/docker-nextcloud#88]
#### Steps to reproduce this issue

1. docker compose pull
2. docker compose up -d
3. docker compose logs -f

#### Expected behaviour

> News Updater should not produce an error in the logs, effectively not running its command.

#### Actual behaviour

> The News Updater container produces the error shown in the logs below.

### Configuration

* Docker version (type `docker --version`) : Docker version 20.10.14, build a224086
* Docker compose version if applicable (type `docker-compose --version`) : Docker compose is installed with DNF as 'docker-compose-plugin'
* Platform (Debian 9, Ubuntu 18.04, ...) : AlmaLinux 8.5
* System info (type `uname -a`) : Linux my.host.name 4.18.0-348.23.1.el8_5.x86_64 SMP Wed Apr 27 05:47:31 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Docker info

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.1-docker)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-348.23.1.el8_5.x86_64
 Operating System: AlmaLinux 8.5 (Arctic Sphynx)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.748GiB
 Name: my.host.name
 ID: YIKC:JVDO:3CJ5:ING5:LDN7:CV4Y:IMA5:HHQX:7IO5:KALW:52MI:SRSK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Logs

```
news_updater  |
news_updater  |
news_updater  |   There are no commands defined in the "news:updater" namespace.
news_updater  |
news_updater  |   Did you mean this?
news_updater  |       maintenance:update
news_updater  |
news_updater  |
news_updater  | 2022-05-03 20:13:00,587 - Nextcloud News Updater - ERROR - Command '['php', '-f', '/var/www/occ', 'news:updater:before-update']' returned non-zero exit status 1.: Trying again in 30 seconds
news_updater  | Traceback (most recent call last):
news_updater  |   File "/usr/lib/python3.9/site-packages/nextcloud_news_updater/api/updater.py", line 69, in run
news_updater  |     self.before_update()
news_updater  |   File "/usr/lib/python3.9/site-packages/nextcloud_news_updater/api/cli.py", line 103, in before_update
news_updater  |     self.cli.run(self.api.before_cleanup_command)
news_updater  |   File "/usr/lib/python3.9/site-packages/nextcloud_news_updater/api/cli.py", line 12, in run
news_updater  |     return check_output(commands)
news_updater  |   File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
news_updater  |     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
news_updater  |   File "/usr/lib/python3.9/subprocess.py", line 528, in run
news_updater  |     raise CalledProcessError(retcode, process.args,
news_updater  | subprocess.CalledProcessError: Command '['php', '-f', '/var/www/occ', 'news:updater:before-update']' returned non-zero exit status 1.
```

**Comment by Amplificator** [comment]
I looked at the closed tickets again and found the solution.

Closing :)
